**Script para filtrar el archivo de clinas por aquellas que fuesen significativas en al menos una variable y que además estuviese anotada.**

In [1]:
#Importamos el archivo original del análisis de clinas
import pandas as pd
filecsv = pd.read_csv(r"Clines.csv",
                   sep =",",skiprows=0)

In [2]:
filecsv.head()

,Portalet_locus_transect,Portalet_waicdiff_npar_AICscale_centre,Portalet_waicdiff_npar_AICscale_v,Portalet_locus,Portalet_S0.prop_1,Portalet_S1.prop_1,Portalet_exp_mean_log_v,Portalet_v_lower_95,Portalet_v_upper_95,Portalet_v_pvalue,...,Portalet_waicdiff2_v,PaysBasco_waicdiff2_v,Portalet_centre_sig_pointplots_minus10,Portalet_centre_sig_clineplots_minus20,Portalet_v_sig_clineplots_minus20,PaysBasco_centre_sig_pointplots_minus10,PaysBasco_centre_sig_clineplots_minus20,PaysBasco_v_sig_clineplots_minus20,Portalet_v_sig_pointplots_minus10,PaysBasco_v_sig_pointplots_minus10
0,chr1_32418580.Portalet,-4.817064,-0.142606,chr1_32418580,0.100000,0.900000,1.024,0.559,1.877,0.939029,...,0.142606,33.924207,False,False,False,False,False,True,False,False
1,chr1_10086195.Portalet,1.355223,1.809742,chr1_10086195,0.233333,0.900000,0.750,0.366,1.539,0.432558,...,-1.809742,28.137857,False,False,False,False,False,True,False,False
2,chr1_13576954.Portalet,-5.992404,2.644444,chr1_13576954,0.166667,0.700000,0.429,0.153,1.206,0.108608,...,-2.644444,12.996241,False,False,False,False,False,False,False,False
3,chr1_22148722.Portalet,-34.079617,-11.814035,chr1_22148722,0.366667,1.000000,2.142,1.337,3.430,0.001524,...,11.814035,21.813070,True,True,False,False,False,True,True,False
4,chr1_41818943.Portalet,0.279974,2.003165,chr1_41818943,0.200000,0.766667,0.773,0.356,1.678,0.515602,...,-2.003165,11.103271,False,False,False,False,False,False,False,False

In [3]:
CTF=[]
CFT=[]
CTT=[]
PTF=[]
PFT=[]
PTT=[]
for a,b,c,d,e in zip(filecsv["Portalet_centre_sig_clineplots_minus20"],filecsv["PaysBasco_centre_sig_clineplots_minus20"],
                     filecsv["Portalet_v_sig_clineplots_minus20"],filecsv["PaysBasco_v_sig_clineplots_minus20"],filecsv["Portalet_locus"]):
    a=str(a)
    b=str(b)
    c=str(c)
    d=str(d)
    e=str(e)
    #print(a,b,c,d,e)
    if a =="True" and b == "True":
        CTT.append(e[e.find("_")+1:])
    if a == "True" and b=="False":
        CTF.append(e[e.find("_")+1:])
    if a=="False" and b=="True":
        CFT.append(e[e.find("_")+1:])
    if c=="True" and d == "True":
        PTT.append(e[e.find("_")+1:])
    if c=="True" and d=="False":
        PTF.append(e[e.find("_")+1:])
    if c=="False" and d=="True":
        PFT.append(e[e.find("_")+1:])

In [4]:
with open ("grasshopperRef.positions", "r") as f:
    fileG=f.readlines()
    ref={}
    for i in fileG:
        if "chr2" in i:
            break
        pos=i.find(":")+1
        end=i.find("\t")
        ID=i[pos:end]
        ref[ID]=[i[(end+1):-1]]
L=[]
with open ("snp_names","r") as f2:
    file2=f2.readlines()
    for i in file2:
        L.append(i)
with open ("snp_names","r") as f2:
    file2=f2.readlines()
    count=0
    for i in ref.keys():
        start=[]
        start=str(ref[i])
        pos=start.find(":")
        pos2=start.find("-")
        pri=int(start[pos+1:pos2])
        sec=int(start[pos2+1:-2])
        number=L[count][:(L[count].find("\t"))]
        if int(number) in range(pri,sec):
            ref[i].append(number)
            count=count+1
            if count == (len(L)+1):
                break

In [5]:
for i in ref.keys():
    try:
        if ref[i][1] in CTT:
            ref[i].append("CTT")
        if ref[i][1] in CTF:
            ref[i].append("CTF")
        if ref[i][1] in CFT:
            ref[i].append("CFT")
        if ref[i][1] in PTT:
            ref[i].append("PTT")
        if ref[i][1] in PTF:
            ref[i].append("PTF")
        if ref[i][1] in PFT:
            ref[i].append("PFT")
    except:
        pass

In [6]:
columns=["Query_accesion","Target_accesion","Sequence Identity","Length","Mismatches","Gap_openings",
         "Query_start","Query_end","Target_start","Target_end","E-value","Bit_score"]

In [7]:
fileGN= pd.read_csv(r"matchesSPU.tsv",
                   sep ="\t",skiprows=0,header=None)

In [8]:
fileGN.columns=columns

In [9]:
fileGN.head()

,Query_accesion,Target_accesion,Sequence Identity,Length,Mismatches,Gap_openings,Query_start,Query_end,Target_start,Target_end,E-value,Bit_score
0,cluster_32,P35041.2,46.8,218,108,5,3308,2661,56,267,1.220000e-51,186.0
1,cluster_32,P35038.2,45.6,206,108,3,3272,2661,72,275,1.590000e-49,180.0
2,cluster_32,P35035.3,43.7,206,112,3,3272,2661,71,274,1.820000e-48,177.0
3,cluster_32,Q07943.1,44.1,202,109,3,3272,2673,51,250,3.440000e-48,176.0
4,cluster_32,P35037.5,41.7,216,119,4,3308,2667,63,273,4.080000e-47,173.0

In [10]:
dic2={}
dummy2=["cluster0"]
count2=0
for i,j,z in zip(fileGN["Query_accesion"],fileGN["Target_accesion"],fileGN["E-value"]) :
    dummy2.append(i)
    count2=count2 +1
    if dummy2[count2] != dummy2[count2-1]:
        dic2[i]=[j,z]

In [17]:
Names=fileGN["Query_accesion"].unique()

In [20]:
header=("SNP","CLUSTER","CENTER","SLOPE","ANNOTATION")
df=pd.DataFrame(columns=header)

In [21]:
SNPL=[]
clusterL=[]
CenterL=[]
SlopeL=[]
AnnotationL=[]
for i in Names:
        SNP=""
        prueba=""
        cluster=""
        A1=""
        center=""
        pen=""
        try:
            prueba=ref[i][2]
            SNP=ref[i][1]
            cluster=i
            try:
                A1=dic2[i][0]
            except:
                A1="Null"
            try:
                if "C" in ref[i][2]:
                    center=ref[i][2]
                else:
                    pen=ref[i][2]
                try:
                    if "C" in ref[i][3]:
                        center=ref[i][3]
                    else:
                        pen=ref[i][3]
                except:
                    if "C" not in center:
                        center="Null"
                    elif "P" not in pen:
                        pen="Null"
            except:
                center="Null"
                pen="Null"
            #print(i,SNP,cluster,center,pen)
            SNPL.append(SNP)
            clusterL.append(cluster)
            CenterL.append(center)
            SlopeL.append(pen)
            AnnotationL.append(A1)
        except:
            pass

In [22]:
df["SNP"]=SNPL
df["CLUSTER"]=clusterL
df["CENTER"]=CenterL
df["SLOPE"]=SlopeL
df["ANNOTATION"]=AnnotationL

In [23]:
df.head()

       SNP      CLUSTER CENTER SLOPE ANNOTATION
0   202731  cluster_107    CTT  Null   Q24239.2
1   604730  cluster_247    CFT  Null   Q9I7U4.3
2   727105  cluster_285    CTT   PFT   Q29BT3.2
3   888185  cluster_332    CTT  Null   Q9NJG9.1
4  1009544  cluster_368    CFT   PFT   Q9GQN5.2

In [24]:
for i in df["SNP"]:
    name=str("chr1_"+i)
    posicion1=df.loc[df["SNP"] == i].index[0]
    posicion2=filecsv.loc[filecsv["Portalet_locus"] == name].index[0]
    c=df.iloc[posicion1]["CENTER"]
    c2=filecsv.iloc[posicion2]["Portalet_centre_sig_clineplots_minus20"]
    c3=filecsv.iloc[posicion2]["PaysBasco_centre_sig_clineplots_minus20"]
    p=df.iloc[posicion1]["SLOPE"]
    p2=filecsv.iloc[posicion2]["Portalet_v_sig_clineplots_minus20"]
    p3=filecsv.iloc[posicion2]["PaysBasco_v_sig_clineplots_minus20"]
    if "Null" == c:
        if str(c2) != "False":
            print("error",i,c,c2)
            break
        if str(c3) != "False":
            print("error",i,c,c3)
            break
    if "C" in str(c):
        if str(c)[1] != str(c2)[0]:
            print("error",i,c,c2)
        if str(c)[2] != str(c3)[0]:
            print("error",i,c,c3)
    if "Null" == p:
        if str(p2) != "False":
            print("error",i,p,p2)
            break
        if str(p3) != "False":
            print("error",i,p,p3)
            break
    if "P" in str(p):
        if str(p)[1] != str(p2)[0]:
            print("error",i,p,p2)
            break
        if str(p)[2] != str(p3)[0]:
            print("error",i,p,p3)
            break
print("Center and Slope are correct")

Center and Slope are correct

In [25]:
point=0
point2=0
for i,j in zip (filecsv["Portalet_v_sig_clineplots_minus20"],filecsv["PaysBasco_v_sig_clineplots_minus20"]):
    if str(i) == "True" and str(j) == "True":
        point=point+1
for i in df["SLOPE"]:
    if str(i) == "PTT":
        point2=point2+1
print(point,len(PTT),point2)

69 69 28

In [27]:
df.to_csv(r"./Analisis_SPU/ClineResultsSPU",sep="\t",index=False,header=header)