**Script para obtener la lista de genes total  y la de cada una de los grupos de interés, además de los backgrounds**

In [15]:
#Importamos el archivo de las clinas significativas, cuyos identificadores serán los que introducimos en el análisis
#funcional

import pandas as pd
filecsv = pd.read_csv(r"ClineResultsSPU",
                   sep ="\t",skiprows=0)

In [16]:
filecsv.head()

       SNP      CLUSTER CENTER SLOPE ANNOTATION
0   202731  cluster_107    CTT  Null   Q24239.2
1   604730  cluster_247    CFT  Null   Q9I7U4.3
2   727105  cluster_285    CTT   PFT   Q29BT3.2
3   888185  cluster_332    CTT  Null   Q9NJG9.1
4  1009544  cluster_368    CFT   PFT   Q9GQN5.2

In [17]:
with open ("genelist","w") as f:
    for i in filecsv["ANNOTATION"]:
        f.write(i[:(i.find("."))])
        f.write("\n")

In [38]:
#Iteramos sobre el dataframe de las clinas y vamos guardando en diferentes listas los identificadores correspondientes

LCPP=[]
CPTT=[]
LCTPT=[]
CCFPF=[]
CTPT=[]
CT=[]
PT=[]
C_TP_T=[]
C_T=[]
P_T=[]
for i,a,b in zip(filecsv["ANNOTATION"],filecsv["CENTER"],filecsv["SLOPE"]):
    
    #La herramienta de DAVID tiene algunos problemas con el siguiente identificador, con lo que lo eliminamos, aún teniéndolo en cuenta
    
    if str(i) != "P02299.4":
        if a == "CTT":
            LCPP.append(i)
        if b == "PTT":
            CPTT.append(i)
        if a =="CTF" and b == "PTF":
            LCTPT.append(i)
        if a =="CFT" and b == "PFT":
            CCFPF.append(i)
        if a =="CTF" or a=="CTT":
            CT.append(i)
        if b=="PTF" or b=="PTT":
            PT.append(i)
        if a =="CTF" or a=="CTT":
            if b=="PTF" or b=="PTT":
                CTPT.append(i)
        if a =="CFT" or a=="CTT":
            C_T.append(i)
        if b=="PFT" or b=="PTT":
            P_T.append(i)
        if a =="CFT" or a=="CTT":
            if b=="PFT" or b=="PTT":
                C_TP_T.append(i)

In [39]:
#Eliminamos los espacios en blanco que tienen algunas listas.

while "" in LCPP:
    LCPP.remove("")
while "" in CPTT:
    CPTT.remove("")
while "" in LCTPT:
    LCTPT.remove("")
while "" in CCFPF:
    CCFPF.remove("")
while "" in CT:
    CT.remove("")
while "" in PT:
    PT.remove("")
while "" in CTPT:
    CTPT.remove("")
while "" in C_T:
    C_T.remove("")
while "" in P_T:
    P_T.remove("")
while "" in C_TP_T:
    C_TP_T.remove("")

In [40]:
#Creamos dos listas más, una para cada transecto, para realizar análisis adicionales

PV=[]
for i in C_T:
    PV.append(i)
for i in P_T:
    if i not in PV:
        PV.append(i)
for i in C_TP_T:
    if i not in PV:
        PV.append(i)

In [41]:
Por=[]
for i in CT:
    Por.append(i)
for i in PT:
    if i not in Por:
        Por.append(i)
for i in CTPT:
    if i not in Por:
        Por.append(i)

In [42]:
#Comprobamos la longitud de las listas

print(len(LCPP),len(CPTT),len(LCTPT),len(CCFPF),len(CT),len(PT),len(CTPT),len(C_T),len(P_T),len(C_TP_T))

241 28 4 29 416 68 17 580 101 85

Guardamos en distintos archivos todos los resultados

In [43]:
with open ("genelistCTT","w") as f:
    for i in LCPP:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [44]:
with open ("genelistPTT","w") as f:
    for i in CPTT:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [45]:
with open ("genelistLCTPT","w") as f:
    for i in LCTPT:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [46]:
with open ("genelistCCFPF","w") as f:
    for i in CCFPF:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [47]:
with open ("genelistCT","w") as f:
    for i in CT:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [48]:
with open ("genelistPT","w") as f:
    for i in PT:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [49]:
with open ("genelistCTPT","w") as f:
    for i in CTPT:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [50]:
with open ("genelistC_TP_T","w") as f:
    for i in C_TP_T:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [51]:
with open ("genelistP_T","w") as f:
    for i in P_T:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [52]:
with open ("genelistC_T","w") as f:
    for i in C_T:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [53]:
with open ("genelistPor","w") as f:
    for i in Por:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [54]:
with open ("genelistPV","w") as f:
    for i in PV:
        name=i
        f.write(name[:(name.find("."))])
        f.write("\n")

In [136]:
#Volvemos a realizar la relación entre cluster y SNP

with open ("grasshopperRef.positions", "r") as f:
    fileG=f.readlines()
    ref={}
    for i in fileG:
        if "chr2" in i:
            break
        pos=i.find(":")+1
        end=i.find("\t")
        ID=i[pos:end]
        ref[ID]=[i[(end+1):-1]]
L=[]
with open ("snp_names","r") as f2:
    file2=f2.readlines()
    for i in file2:
        L.append(i)
with open ("snp_names","r") as f2:
    file2=f2.readlines()
    count=0
    for i in ref.keys():
        start=[]
        start=str(ref[i])
        pos=start.find(":")
        pos2=start.find("-")
        pri=int(start[pos+1:pos2])
        sec=int(start[pos2+1:-2])
        number=L[count][:(L[count].find("\t"))]
        if int(number) in range(pri,sec):
            ref[i].append(number)
            count=count+1
            if count == (len(L)+1):
                break

In [137]:
#Abrimos el archivo de nuestra anotación con swissprot, que servirá como background general

fileIns = pd.read_csv(r"matchesSPU.tsv",
                   sep ="\t",skiprows=0,header=None)
fileIns.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,cluster_32,P35041.2,46.8,218,108,5,3308,2661,56,267,1.220000e-51,186.0
1,cluster_32,P35038.2,45.6,206,108,3,3272,2661,72,275,1.590000e-49,180.0
2,cluster_32,P35035.3,43.7,206,112,3,3272,2661,71,274,1.820000e-48,177.0
3,cluster_32,Q07943.1,44.1,202,109,3,3272,2673,51,250,3.440000e-48,176.0
4,cluster_32,P35037.5,41.7,216,119,4,3308,2667,63,273,4.080000e-47,173.0

In [138]:
#Nos quedamos solo con el primer hit por cluster
dummy=["cluster0"]
count2=0
for i,j,z in zip(fileIns[0],fileIns[1],fileIns[10]) :
    dummy.append(i)
    count2=count2 +1
    if dummy[count2] != dummy[count2-1]:
        ref[i].append(j)

In [139]:
#Guardamos en un archivo los identificadores
with open ("backgroundWholeSPU","w") as f:
    for i in ref.keys():
        try:
            name=ref[i][2]
            f.write(name[:(name.find("."))])
            f.write("\n")
        except:
            pass

In [140]:
#Al haber modificado antes el diccionario, lo volvemos a hacer para tener las referencias
with open ("grasshopperRef.positions", "r") as f:
    fileG=f.readlines()
    ref={}
    for i in fileG:
        if "chr2" in i:
            break
        pos=i.find(":")+1
        end=i.find("\t")
        ID=i[pos:end]
        ref[ID]=[i[(end+1):-1]]
L=[]
with open ("snp_names","r") as f2:
    file2=f2.readlines()
    for i in file2:
        L.append(i)
with open ("snp_names","r") as f2:
    file2=f2.readlines()
    count=0
    for i in ref.keys():
        start=[]
        start=str(ref[i])
        pos=start.find(":")
        pos2=start.find("-")
        pri=int(start[pos+1:pos2])
        sec=int(start[pos2+1:-2])
        number=L[count][:(L[count].find("\t"))]
        if int(number) in range(pri,sec):
            ref[i].append(number)
            count=count+1
            if count == (len(L)+1):
                break

In [141]:
# Ahora creamos el background con solo las clinas, significativas o no
filecsv = pd.read_csv(r"Clines.csv",
                   sep =",",skiprows=0)

In [142]:
filecsv.head()

,Portalet_locus_transect,Portalet_waicdiff_npar_AICscale_centre,Portalet_waicdiff_npar_AICscale_v,Portalet_locus,Portalet_S0.prop_1,Portalet_S1.prop_1,Portalet_exp_mean_log_v,Portalet_v_lower_95,Portalet_v_upper_95,Portalet_v_pvalue,...,Portalet_waicdiff2_v,PaysBasco_waicdiff2_v,Portalet_centre_sig_pointplots_minus10,Portalet_centre_sig_clineplots_minus20,Portalet_v_sig_clineplots_minus20,PaysBasco_centre_sig_pointplots_minus10,PaysBasco_centre_sig_clineplots_minus20,PaysBasco_v_sig_clineplots_minus20,Portalet_v_sig_pointplots_minus10,PaysBasco_v_sig_pointplots_minus10
0,chr1_32418580.Portalet,-4.817064,-0.142606,chr1_32418580,0.100000,0.900000,1.024,0.559,1.877,0.939029,...,0.142606,33.924207,False,False,False,False,False,True,False,False
1,chr1_10086195.Portalet,1.355223,1.809742,chr1_10086195,0.233333,0.900000,0.750,0.366,1.539,0.432558,...,-1.809742,28.137857,False,False,False,False,False,True,False,False
2,chr1_13576954.Portalet,-5.992404,2.644444,chr1_13576954,0.166667,0.700000,0.429,0.153,1.206,0.108608,...,-2.644444,12.996241,False,False,False,False,False,False,False,False
3,chr1_22148722.Portalet,-34.079617,-11.814035,chr1_22148722,0.366667,1.000000,2.142,1.337,3.430,0.001524,...,11.814035,21.813070,True,True,False,False,False,True,True,False
4,chr1_41818943.Portalet,0.279974,2.003165,chr1_41818943,0.200000,0.766667,0.773,0.356,1.678,0.515602,...,-2.003165,11.103271,False,False,False,False,False,False,False,False

In [147]:
#Nos tenemos que quedar solo con las clinas que estén anotadas
fileIns = pd.read_csv(r"matchesSPU.tsv",
                   sep ="\t",skiprows=0,header=None)

dummy=["cluster0"]
count2=0

In [148]:
fileIns.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,cluster_32,P35041.2,46.8,218,108,5,3308,2661,56,267,1.220000e-51,186.0
1,cluster_32,P35038.2,45.6,206,108,3,3272,2661,72,275,1.590000e-49,180.0
2,cluster_32,P35035.3,43.7,206,112,3,3272,2661,71,274,1.820000e-48,177.0
3,cluster_32,Q07943.1,44.1,202,109,3,3272,2673,51,250,3.440000e-48,176.0
4,cluster_32,P35037.5,41.7,216,119,4,3308,2667,63,273,4.080000e-47,173.0

In [153]:
#Nos quedamos con las clinas que esten anotadas
for i in filecsv["Portalet_locus"]:
    locus=i[(i.find("_"))+1:]
    for j in ref.keys():
        try:
            if ref[j][1]==locus:
                for i,j,z in zip(fileIns[0],fileIns[1],fileIns[10]) :
                    dummy.append(i)
                    count2=count2 +1
                    if dummy[count2] != dummy[count2-1]:
                        ref[i].append(j)
        except:
            pass

In [154]:
#Guardamos la anotación de las clinas
with open ("backgroundClineSPU","w") as f:
    for i in ref.keys():
        print(ref[i])
        try:
            name=ref[i][2]
            f.write(name[:(name.find("."))])
            f.write("\n")
        except:
            pass

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)