**Script para comparar dos anotaciones, se puede realizar con dos anotaciones con el mismo formato o con distinto**

**Javier Gutiérrez Corral**
**09/12/2023**

In [1]:
#Se importan los paquetes necesarios

import pandas as pd

In [2]:
#Se abre una de las anotaciones

file = pd.read_csv(r"vsInsectae.csv",
                   sep =";",skiprows=0)

In [3]:
file.head()

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
0,cluster_6,sp|P23803|ODD_DROME,35.417,48,29,1,8115,8252,195,242,3.400000e-02,38.1
1,cluster_8,sp|P80703|APLP3_GALME,29.167,72,41,1,2185,2000,32,103,7.800000e+00,28.5
2,cluster_23,sp|P08970|SUHW_DROME,29.644,253,164,9,3243,3986,292,535,7.460000e-23,105.0
3,cluster_23,sp|P08970|SUHW_DROME,28.251,223,115,8,3243,3896,382,564,2.870000e-14,77.8
4,cluster_23,sp|P08970|SUHW_DROME,27.184,206,124,9,3129,3743,434,614,9.660000e-08,56.2

In [4]:
#Se añade a un diccionario el identificador como clave y la anotación y el e valor como valor

dic={}
dummy=["cluster0"]
count=0
qseqid=[]

for i,j,z in zip(file["qseqid"],file["sseqid"],file["evalue"]) :
    
    #Se filtran las anotaciones que tengan un e-valor superior a cierto valor
    if "e" in str(z) or str(z) == "0.0" or str(z) == "0.001":       
        qseqid.append(i)
        dummy.append(i)
        count=count +1
        if dummy[count] != dummy[count-1]:
            
            dic[i]=[j,z]

In [5]:
#Se realiza lo mismo con la otra anotación

columns=["Query_accesion","Target_accesion","Sequence Identity","Length","Mismatches","Gap_openings",
         "Query_start","Query_end","Target_start","Target_end","E-value","Bit_score"]
file2 = pd.read_csv(r"matchesNRU.tsv",
                   sep ="\t",skiprows=0)
file2.columns=columns
file2.head()

,Query_accesion,Target_accesion,Sequence Identity,Length,Mismatches,Gap_openings,Query_start,Query_end,Target_start,Target_end,E-value,Bit_score
0,cluster_6,XP_047101492.1,62.1,3471,1119,46,3,9896,4519,7964,0.0,3455.0
1,cluster_6,XP_049843621.1,61.6,3455,1137,47,3,9896,3569,6998,0.0,3428.0
2,cluster_6,XP_049843616.1,61.6,3455,1137,47,3,9896,3652,7081,0.0,3428.0
3,cluster_6,XP_049843618.1,61.6,3455,1137,47,3,9896,3652,7081,0.0,3428.0
4,cluster_6,XP_049843617.1,61.6,3455,1137,47,3,9896,3647,7076,0.0,3428.0

In [6]:
#Se recupera la primera anotación de cada cluster

dic2={}
dummy2=["cluster0"]
count2=0

for i,j,z in zip(file2["Query_accesion"],file2["Target_accesion"],file2["E-value"]) :
    dummy2.append(i)
    count2=count2 +1
    if dummy2[count2] != dummy2[count2-1]:
        dic2[i]=[j,z]

In [7]:
#Para comprobar cuantos transcritos hay anotados

count=0
for i in dic2.keys():
    count=count+1

In [8]:
print(count)

11684

In [9]:
#Para cargar otra anotación con el mismo formato

columns=["Query_accesion","Target_accesion","Sequence Identity","Length","Mismatches","Gap_openings",
         "Query_start","Query_end","Target_start","Target_end","E-value","Bit_score"]
file3 = pd.read_csv(r"matchesNR.tsv",
                   sep ="\t",skiprows=0)
file3.columns=columns
file3.head()

,Query_accesion,Target_accesion,Sequence Identity,Length,Mismatches,Gap_openings,Query_start,Query_end,Target_start,Target_end,E-value,Bit_score
0,cluster_6,XP_047101492.1,62.1,3471,1119,46,3,9896,4519,7964,0.0,3455.0
1,cluster_6,XP_049843621.1,61.6,3455,1137,47,3,9896,3569,6998,0.0,3428.0
2,cluster_6,XP_049843616.1,61.6,3455,1137,47,3,9896,3652,7081,0.0,3428.0
3,cluster_6,XP_049843618.1,61.6,3455,1137,47,3,9896,3652,7081,0.0,3428.0
4,cluster_6,XP_049843617.1,61.6,3455,1137,47,3,9896,3647,7076,0.0,3428.0

In [10]:
# Se recupera la primera anotación de cada cluster

dic3={}
dummy3=["cluster0"]
count3=0

for i,j,z in zip(file3["Query_accesion"],file3["Target_accesion"],file3["E-value"]) :
    dummy3.append(i)
    count3=count3 +1
    if dummy3[count3] != dummy3[count3-1]:
        dic3[i]=[j,z]

In [11]:
count=0
for i in dic3.keys():
    count=count+1

In [12]:
print(count)

11686

In [13]:
#En una lista se añaden todos los accesion que se quiere comparar

Names1=file2["Query_accesion"].unique()
Names2=file3["Query_accesion"].unique() #si es con la otra anotación file["qseqid"].unique()
Names=[]

for i,j in zip(Names1,Names2):
    if i not in Names:
        Names.append(i)
    if j not in Names:
        Names.append(j)

In [14]:
'''
Se guarda en un archivo la comprobación con un resumen final, además de los e valores que son distintos
por si se quiere comparar dos anotaciones muy parecidas
'''

with open("Comparation5nrvnru.txt","w") as f:
    
    MF=0
    TF=0
    problem=[]
    EV=[]
    EV2=[]
    cluster=[]
    cluster2=[]
    
    for i in Names:
        
        f.write("Comparing annotation for:")
        f.write(i)
        f.write("\n")
        f.write("My annotation:")
        
        '''
        Se utiliza un sistema de excepciones porque si una anotación no se encuentra en uno de los dos archivos da error.
        En vez de eso se quiere guardar como no encontrado o no anotado
        '''
        
        try:
            f.write(str(dic2[i][0]))
        except KeyError:
               f.write("Not found")
               problem.append(i)
               MF=MF+1
        f.write("\n")
        f.write("Their annotation:")
        try:
            f.write(str(dic3[i][0]))
        except KeyError:
               f.write("Not found")
               problem.append(i)
               TF=TF+1
        f.write("\n")
        f.write("E-values")
        f.write("\n")
        f.write("Our:")
        try:
            f.write(str(dic2[i][1]))
            EV.append(str(dic2[i][1]))
        except KeyError:
            f.write("Not found")
            EV.append("none")
        f.write("\n")
        f.write("Their:")
        try:
            f.write(str(dic3[i][1]))
            EV2.append(str(dic3[i][1]))
        except KeyError:
            f.write("Not found")
            EV2.append("none")
        f.write("\n")
        
    f.write("Clusters not found in our annotation")
    f.write(str(MF))
    f.write("\n")
    f.write("Clusters not found in their annotation")
    f.write(str(TF))

In [15]:
#Para ver el resultado de cada anotación

for i in problem:
    print(i)
    try:
        print(dic2[i])
    except:
        print("no la tenemos",i)
    try:
        print(dic3[i])
    except:
        print("no la tienen", i)
    print("\n")

cluster_10321
no la tenemos cluster_10321
['XP_049841424.1', 6.88e-07]


cluster_16246
no la tenemos cluster_16246
['XP_047099311.1', 8.06e-10]

In [16]:
#Comparar aquellos clusters que tienen e valores distintos, solo sirve para anotaciones muy parecidas

for i in Names:
    try:
        if dic2[i] != dic3[i]:
            print(i,dic2[i],dic3[i])
    except:
        pass

cluster_1765 ['XP_046983358.1', 4.76e-68] ['XP_049796148.1', 1.93e-69]
cluster_5544 ['1GL1_I', 6.91e-05] ['XP_048000829.1', 0.000347]
cluster_6462 ['CAH1380380.1', 3.19e-05] ['XP_049841424.1', 2.81e-08]
cluster_12984 ['XP_032687100.1', 5.34e-11] ['KAG5865645.1', 1.86e-11]
cluster_13905 ['XP_049961998.1', 3.32e-07] ['XP_047116270.1', 6.77e-07]